import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import MyEditor from '../components/MyEditor'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - Thread Builder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='w-10/12 md:w-6/12 lg:w-4/12 mx-auto'>
        <MyEditor />
      </div>
      <div className='w-10/12 md:w-6/12 lg:w-4/12 mx-auto'>
        <Footer />
      </div>
    </div>
  )
}
